# Site settings
title: Jack Dunn
email: jack.dunn.nz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a third-year doctoral candidate at the MIT Operations Research Center.
  My primary research interest is the intersection of modern optimization
  with statistics and machine learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jack.dunn.nz" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  JackDunnNZ

# Build settings
markdown: kramdown
